// Manual práctico del CRM: cada entrada tiene keywords para el buscador de ayuda.
// El HelpPanel puntúa las entradas según coincidencia con la pregunta del usuario.

export interface EntradaManual {
  id: string
  titulo: string
  categoria: string
  keywords: string
  pasos: string[]
  tip?: string
}

export const MANUAL: EntradaManual[] = [
  {
    id: 'crear-cliente',
    titulo: 'Crear un cliente nuevo',
    categoria: 'Clientes',
    keywords: 'crear nuevo cliente agregar lead persona registrar ingresar contacto prospecto',
    pasos: [
      'Ve a "Clientes" en el menú lateral (o presiona Ctrl+K y escribe "nuevo cliente").',
      'Haz click en el botón naranjo "Nuevo cliente".',
      'Completa el modo rápido: solo Nombre, Teléfono y Canal de origen.',
      'Si necesitas más campos (correo, RUT, tipo de cliente...), haz click en "Modo completo".',
      'En "Modo completo" eliges el "Tipo de cliente" (Paciente, Alumni, Asistente a talleres, Prospecto o Empresa/B2B): es su relación con Renova, no la actividad.',
      'El campo "Actividades", separado del tipo, te deja asignar programas del catálogo: al guardarlos se registran solos en la pestaña Actividades del cliente para gestionarlos.',
      'Haz click en "Guardar". El cliente queda en etapa "Nuevo".',
    ],
    tip: 'No te detengas a llenar todos los campos: con nombre y teléfono basta para empezar. Si el cliente es paciente, asigna su Terapeuta — así cada pago genera la boleta de honorarios automáticamente.',
  },
  {
    id: 'kpi-comercial',
    titulo: 'Ver el KPI Comercial por campaña',
    categoria: 'Reportes',
    keywords: 'kpi comercial embudo funnel tasas conversion campaña actividad leads contactados cotizados inscritos asesores reporte indicadores',
    pasos: [
      'Ve a "Reportes" en el menú lateral.',
      'Abre la pestaña "📊 KPI Comercial" y haz click en "Cargar".',
      'Verás una fila por campaña (actividad) con el embudo: Leads → Contactados → Seguimiento activo → Interesados → En pausa → Cotizados → Inscritos.',
      'A la derecha están las tasas: contacto, cotización, cierre y conversión global. La fila TOTAL consolida todas las campañas.',
      'Con "Exportar Excel" generas la planilla lista para enviar a los asesores.',
    ],
    tip: 'Los números salen en vivo del funnel y de los seguimientos: mientras más completo el registro diario, más fiel el KPI.',
  },
  {
    id: 'etapa-en-pausa',
    titulo: 'Marcar un lead "En pausa"',
    categoria: 'Seguimiento',
    keywords: 'en pausa pospuesto precio tiempo reactivar etapa funnel kanban lateral mas adelante despues no ahora',
    pasos: [
      'En el Kanban del funnel (o en la ficha del cliente), mueve la oportunidad a la columna "En pausa".',
      'Úsala cuando la persona indica que por ahora, por precio o tiempo, posterga su avance — sin un cierre definitivo.',
      'El lead queda separado de los que siguen avanzando y suma a la "tasa de continuidad" del KPI.',
      'Más adelante puedes reactivarlo moviéndolo de vuelta a la etapa que corresponda.',
    ],
    tip: 'Revisa "En pausa" cada cierto tiempo: es tu lista de personas a reactivar con un mensaje cálido y una pregunta abierta.',
  },
  {
    id: 'acciones-masivas',
    titulo: 'Registrar acciones de seguimiento masivas (correo/WhatsApp por actividad)',
    categoria: 'Seguimiento',
    keywords: 'masivo masiva importar exportar plantilla excel correo whatsapp llamada actividad campaña envio masivo seguimientos varios clientes a la vez',
    pasos: [
      'En "Seguimientos" (vista Por cliente), filtra por la actividad que vas a trabajar.',
      'Haz click en "Plantilla" para descargar el Excel con esos clientes (nombre y contacto) y columnas "Correo enviado / WhatsApp enviado / Llamada (fecha)" y "Nota".',
      'Llena la fecha en la columna del canal que usaste (puedes llenar varias) y, si quieres, una nota. Deja en blanco lo que no aplique.',
      'Vuelve a "Seguimientos", con la misma actividad filtrada, y haz click en "Importar acciones" para subir el Excel lleno.',
      'Verás una VISTA PREVIA: cuántos seguimientos se registrarán, cuántos clientes no coinciden y si alguna fecha quedó dudosa. Nada se guarda hasta que pulses "Confirmar e importar".',
      'Al confirmar, el sistema registra un seguimiento por cada acción marcada, etiquetado con la actividad, para todos los clientes de la planilla a la vez.',
    ],
    tip: 'Ideal para envíos masivos: mandas el correo y el WhatsApp a tu lista, anotas las fechas en la plantilla y con un click quedan registrados todos los seguimientos.',
  },
  {
    id: 'vista-hoy',
    titulo: 'Saber a quién contactar hoy',
    categoria: 'Seguimiento',
    keywords: 'hoy contactar quien llamar pendientes agenda dia atrasados enfriandose urgentes',
    pasos: [
      'Haz click en "Hoy" (primera opción del menú, ícono de sol ☀️).',
      'Verás tres listas: Atrasados (rojo), Agendados para hoy, y Enfriándose (clientes con 7+ días sin contacto en etapa activa).',
      'Trabaja la lista de arriba hacia abajo: cada fila tiene botones de WhatsApp, llamada y "Contactado".',
      'Al registrar el contacto, elige cuándo recontactar — así el cliente vuelve a aparecer en "Hoy" en la fecha correcta.',
    ],
    tip: 'Haz de "Hoy" tu rutina de la mañana: si la trabajas completa cada día, ningún lead se enfría.',
  },
  {
    id: 'registrar-seguimiento',
    titulo: 'Registrar un contacto / seguimiento',
    categoria: 'Seguimiento',
    keywords: 'registrar seguimiento contacto llamada whatsapp correo anotar conversacion nota',
    pasos: [
      'Opción rápida: en la lista de Clientes o en "Hoy", pasa el mouse sobre la fila y haz click en el botón "Contactado" (✓).',
      'Elige el tipo de contacto (llamada, whatsapp, correo, otro).',
      'Escribe una nota breve (opcional pero recomendado).',
      'Elige cuándo recontactar: Mañana, 3 días, 1 semana o Sin fecha.',
      'Haz click en "✓ Guardar contacto". Listo: seguimiento registrado y próximo contacto agendado.',
    ],
    tip: 'Si necesitas registrar un seguimiento más detallado (con fecha pasada o actividad asociada), usa "Seguimientos" → "Nuevo seguimiento".',
  },
  {
    id: 'whatsapp-plantilla',
    titulo: 'Enviar WhatsApp con plantilla',
    categoria: 'Seguimiento',
    keywords: 'whatsapp plantilla mensaje enviar template texto predeterminado',
    pasos: [
      'En la vista "Hoy", haz click en el botón verde "WhatsApp" de cualquier cliente.',
      'Se despliega el menú de plantillas con el mensaje ya personalizado (nombre y actividad del cliente).',
      'Haz click en la plantilla: se abre WhatsApp con el mensaje listo para enviar, y el seguimiento se registra solo.',
      'En WhatsApp solo revisa el texto y presiona enviar.',
    ],
    tip: 'Puedes crear o editar plantillas en Configuración → Plantillas de WhatsApp. Usa {nombre} y {actividad} como variables.',
  },
  {
    id: 'plantillas-editar',
    titulo: 'Crear o editar plantillas de WhatsApp',
    categoria: 'Configuración',
    keywords: 'plantilla crear editar eliminar mensaje predeterminado variable nombre actividad',
    pasos: [
      'Ve a "Configuración" en el menú lateral.',
      'Baja hasta la sección "Plantillas de WhatsApp".',
      'Para crear: escribe el nombre y el mensaje, y haz click en "Agregar".',
      'Usa {nombre} donde quieras que aparezca el primer nombre del cliente, y {actividad} para su última actividad.',
      'Para eliminar una plantilla, haz click en el ícono de basurero.',
    ],
  },
  {
    id: 'registrar-pago',
    titulo: 'Registrar un pago',
    categoria: 'Pagos',
    keywords: 'registrar pago nuevo cobro abono monto factura transferencia sin cobro fecha actividad cuotas',
    pasos: [
      'Opción 1: en el perfil del cliente, haz click en el botón verde "Pago" (o en la pestaña "Actividades y pagos").',
      'Opción 2: en "Pagos" del menú, haz click en "Nuevo pago" y busca el cliente.',
      'Selecciona la actividad: aparecen primero las del cliente y luego el catálogo completo. Si eliges una nueva, se agrega sola a su perfil.',
      'Elige la forma de cobro: "Pago único" o "Plan de cuotas".',
      'Pago único: completa monto, fecha de pago y fecha de la actividad (si son distintas), método y estado.',
      'Si no hay cobro (beca, cortesía), usa el botón "Sin cobro" junto al método.',
      'Si requiere factura, marca el checkbox y anota el N° cuando se emita. El campo "Facturación interna" es el folio para el registro SII.',
      'Haz click en "Guardar". Si el cliente tiene terapeuta asignado, se genera automáticamente la boleta de honorarios pendiente.',
    ],
  },
  {
    id: 'plan-cuotas',
    titulo: 'Cobrar en cuotas (plan de pago) y seguir el semáforo',
    categoria: 'Pagos',
    keywords: 'cuotas plan pago dividir partes vencimiento semaforo cobranza abono marcar pagada cuota mensual cobrar a plazo',
    pasos: [
      'Al registrar un pago (botón verde "Pago" en la ficha, o "Nuevo pago" en Pagos), elige "Plan de cuotas".',
      'Indica el número de cuotas, el monto total y la fecha de la primera cuota: el sistema reparte parejo y calcula los vencimientos mensuales.',
      'Ajusta a mano cualquier monto o fecha si lo necesitas; "Recalcular parejo" vuelve al reparto automático.',
      'Guarda: las cuotas quedan listadas en la ficha del cliente, bajo su actividad, cada una con su semáforo (verde al día, ámbar si vence en 3 días o menos, rojo vencida).',
      'Cuando llega el abono de una cuota, haz click en "Marcar pagada". Si te equivocas, "Deshacer" la vuelve a pendiente.',
    ],
    tip: 'Cada cuota pagada cuenta como ingreso en su propia fecha. En la página Pagos, los pagos con plan muestran la etiqueta "Plan de cuotas" — se gestionan cuota a cuota desde la ficha.',
  },
  {
    id: 'cobranza',
    titulo: 'Ver la cobranza: cuotas por cobrar de todos',
    categoria: 'Pagos',
    keywords: 'cobranza cuotas por cobrar vencidas semaforo morosos pendiente vencimiento recordar whatsapp por cliente prioridad',
    pasos: [
      'Ve a "Cobranza" en el menú lateral (ícono de calendario con reloj).',
      'Arriba ves los totales: total por cobrar, vencido, por vencer (≤3 días) y cuántos clientes tienen cuotas.',
      'Pestaña "Por cuota": cada cuota con su semáforo (rojo vencida, ámbar por vencer, verde al día). Filtra por Vencidas o Por vencer.',
      'Usa los botones de WhatsApp (mensaje en tono PNL ya listo), llamada o correo para contactar al instante.',
      'Pestaña "Por cliente": el resumen ordenado por prioridad, con el total por cobrar y el próximo vencimiento de cada persona.',
      'Botón "Exportar Excel" para bajar la lista filtrada.',
    ],
    tip: 'Las cuotas vencidas se marcan solas cada día. Revisa Cobranza cada mañana junto con la vista "Hoy".',
  },
  {
    id: 'marcar-pagado',
    titulo: 'Marcar un pago pendiente como pagado',
    categoria: 'Pagos',
    keywords: 'marcar pagado pendiente cambiar estado pago cobrar confirmar',
    pasos: [
      'Ve a "Pagos" en el menú lateral.',
      'Filtra por estado "Pendiente" si quieres ver solo los pendientes.',
      'En la fila del pago, haz click en el botón verde "Pagado" (aparece solo en pagos pendientes o parciales).',
      'Listo — el estado cambia y los totales se actualizan.',
    ],
    tip: 'También puedes editar el pago completo desde el perfil del cliente, pestaña "Actividades y pagos", con el ícono de lápiz. Si el pago es un plan de cuotas, márcalo cuota a cuota en la ficha.',
  },
  {
    id: 'tipos-actividades',
    titulo: 'Agregar un tipo de cliente nuevo',
    categoria: 'Clientes',
    keywords: 'tipo cliente nuevo agregar crear categoria actividad no aparece',
    pasos: [
      'Los tipos de cliente son el catálogo de Actividades — están 100% sincronizados.',
      'Ve a "Actividades" en el menú y haz click en "Nueva actividad".',
      'Ponle nombre y tipo. Las fechas son opcionales (déjalas vacías si es indefinida).',
      'Listo: aparecerá como opción de "Tipo de cliente" al crear o editar clientes.',
      'Al asignarla, la asistencia se registra automáticamente en el perfil del cliente.',
    ],
    tip: 'Si agregaste un tipo y no aparece, es porque debe crearse como Actividad (no en Configuración).',
  },
  {
    id: 'honorarios',
    titulo: 'Boletas de honorarios (docentes y terapeutas)',
    categoria: 'Pagos',
    keywords: 'honorarios boleta docente terapeuta retencion sii liquido bruto emitir marcar prestador',
    pasos: [
      'Primero marca al prestador: en su perfil de cliente, haz click en el botón "🎓 Docente" o "🩺 Terapeuta" junto a su nombre.',
      'Terapias (automático): asigna el terapeuta al paciente (campo "Terapeuta" del formulario, se elige de la lista de terapeutas marcados). Cada pago de ese paciente crea sola una boleta "Pendiente" en Honorarios, con el monto del pago como referencia.',
      'Clases (manual): en Honorarios, haz click en "Nueva boleta" y busca al docente en el listado de clientes.',
      'Ingresa el monto LÍQUIDO: el sistema calcula la retención vigente y el monto bruto a boletear según la ley chilena.',
      'Cuando el prestador emita la boleta, anota su N° — pasa a estado "Emitida".',
      'Las boletas del prestador aparecen también en su perfil de cliente (pestaña Honorarios).',
    ],
    tip: 'La columna "Pago ref." muestra lo que pagó el paciente — es solo referencial: el monto a boletear se ingresa aparte como líquido.',
  },
  {
    id: 'gastos',
    titulo: 'Registrar gastos de la empresa y arriendo de sala',
    categoria: 'Pagos',
    keywords: 'gastos empresa arriendo sala box boleta factura registro compras',
    pasos: [
      'Ve a "Gastos empresa" en el menú lateral.',
      'Pestaña "Gastos varios": fecha, ítem, descripción, tienda, tipo de pago, boleta/factura con su N°, y total.',
      'Pestaña "Arriendo sala": profesional, paciente/motivo, fechas de sesión y pago, valor y factura.',
      'Filtra por mes con el selector — los totales (boleta/factura/general) se calculan solos, igual que en el Excel.',
    ],
    tip: 'Registra el gasto apenas ocurra, con la boleta en la mano — toma 20 segundos y se acabaron las planillas sueltas.',
  },
  {
    id: 'cambiar-etapa',
    titulo: 'Mover una oportunidad de etapa (funnel por actividad)',
    categoria: 'Clientes',
    keywords: 'etapa funnel mover cambiar avanzar negociando inscrito interesado pipeline embudo oportunidad actividad chip',
    pasos: [
      'El funnel es POR actividad: una persona puede estar en distinta etapa según la actividad (ej. inscrita en la clase y "Con interés" para el taller, al mismo tiempo).',
      'Abre el perfil del cliente y entra a la pestaña "Actividades y pagos".',
      'Cada actividad tiene su propio menú de etapa: haz click y elige la nueva. Se guarda solo.',
      'Si la persona aún no tiene esa actividad, usa "Sumar una actividad al funnel" arriba de la lista.',
      'En la lista de Clientes, la columna "Funnel" muestra los chips "Actividad: Etapa" de cada persona (solo lectura; para cambiarlos, abre su ficha).',
    ],
    tip: 'Al registrar un pago de una actividad, recuerda avanzar su oportunidad a "Inscrito" en esa misma pestaña.',
  },
  {
    id: 'buscar-cliente',
    titulo: 'Buscar un cliente rápido',
    categoria: 'Clientes',
    keywords: 'buscar encontrar cliente ctrl k busqueda rapida atajo teclado tilde acento nombre completo palabras',
    pasos: [
      'Presiona Ctrl+K (o Cmd+K en Mac) desde cualquier pantalla, o usa el buscador de la página Clientes.',
      'Escribe nombre, teléfono o correo. La búsqueda ignora tildes y entiende palabras sueltas: "maria perez" encuentra a "María José Pérez Soto".',
      'Usa las flechas ↑↓ y Enter para abrir su perfil, o haz click directo.',
      'Desde el resultado también puedes abrir WhatsApp sin entrar al perfil.',
    ],
  },
  {
    id: 'importar-excel',
    titulo: 'Importar clientes desde Excel',
    categoria: 'Datos',
    keywords: 'importar excel subir archivo carga masiva planilla',
    pasos: [
      'Ve a "Importar Excel" en el menú lateral.',
      'Arrastra tu archivo .xlsx o haz click para seleccionarlo.',
      'El sistema detecta las columnas automáticamente — revisa la vista previa.',
      'Confirma la importación. Los clientes quedan creados con sus datos.',
    ],
    tip: 'Puedes descargar la plantilla oficial desde la misma pantalla para asegurar el formato correcto.',
  },
  {
    id: 'exportar',
    titulo: 'Exportar clientes o la base completa',
    categoria: 'Datos',
    keywords: 'exportar descargar excel pdf base respaldo backup',
    pasos: [
      'Ve a "Clientes" y haz click en el botón "Exportar".',
      'Elige: Excel (filtrado), PDF (filtrado) o Base completa.',
      '"Filtrado" exporta lo que estás viendo (respeta búsqueda y filtros); "Base completa" incluye todo con seguimientos y pagos.',
      'El archivo se descarga automáticamente.',
    ],
  },
  {
    id: 'reportes',
    titulo: 'Ver reportes (por cobrar, cumpleaños, asistentes...)',
    categoria: 'Datos',
    keywords: 'reportes informes cumpleanos cobrar asistentes procedencia canal pendientes sin contacto incompletos telefono correo facturacion',
    pasos: [
      'Ve a "Reportes" en el menú lateral.',
      'Elige la pestaña: Por cobrar, Asistentes por actividad, Pagos por actividad, Cumpleaños del mes, Procedencias, Facturación o "Sin contacto".',
      'La pestaña "Sin contacto" lista los clientes sin teléfono ni correo, para completar su perfil.',
      'Cada reporte permite contacto rápido (WhatsApp/llamada) y exportación a Excel.',
    ],
  },
  {
    id: 'crear-usuario',
    titulo: 'Crear un usuario nuevo del sistema',
    categoria: 'Configuración',
    keywords: 'usuario crear nuevo acceso cuenta contrasena password equipo',
    pasos: [
      'Ve a "Configuración" en el menú lateral.',
      'En la sección "Usuarios", haz click en "Nuevo usuario".',
      'Ingresa el correo y una contraseña (mínimo 6 caracteres).',
      'Comparte las credenciales con la persona — podrá cambiar su contraseña después.',
    ],
  },
  {
    id: 'cambiar-contrasena',
    titulo: 'Cambiar la contraseña de un usuario',
    categoria: 'Configuración',
    keywords: 'cambiar contrasena password clave olvide acceso recuperar',
    pasos: [
      'Ve a "Configuración" → sección "Usuarios".',
      'En la fila del usuario, haz click en el ícono de llave 🔑.',
      'Escribe la nueva contraseña y guarda.',
    ],
  },
  {
    id: 'tema-dorado',
    titulo: 'Cambiar entre tema Claro y Dorado',
    categoria: 'Configuración',
    keywords: 'tema dorado claro oscuro color apariencia modo',
    pasos: [
      'En la barra superior derecha, haz click en el botón "Dorado" (o "Claro" si ya estás en dorado).',
      'La preferencia se guarda en este navegador automáticamente.',
    ],
  },
  {
    id: 'tutorial',
    titulo: 'Capacitarse desde cero (usuarios nuevos)',
    categoria: 'Configuración',
    keywords: 'tutorial capacitacion aprender nuevo usuario empezar partir induccion entrenamiento',
    pasos: [
      'Ve a "Tutorial" en el menú lateral (ícono de birrete).',
      'Avanza por los 6 capítulos en orden: rutina diaria, contactos, clientes y funnel, pagos, dashboard, y atajos.',
      'Marca cada capítulo como entendido — tu progreso se guarda automáticamente.',
      'Toma unos 15 minutos. Al terminar, abre la vista "Hoy" y trabaja tu primera lista real.',
    ],
    tip: 'Ideal para el primer día de una persona nueva en el equipo: entregarle su acceso y pedirle que complete el tutorial antes de empezar.',
  },
  {
    id: 'editar-eliminar-cliente',
    titulo: 'Editar o eliminar un cliente',
    categoria: 'Clientes',
    keywords: 'editar eliminar borrar cliente modificar datos corregir',
    pasos: [
      'Abre el perfil del cliente (click en su nombre o Ctrl+K).',
      'Para editar: haz click en el ícono de lápiz junto al nombre y modifica los campos.',
      'Para eliminar: haz click en el botón "..." → "Eliminar cliente" y confirma.',
      'Ojo: eliminar un cliente borra también sus seguimientos, pagos y asistencias, y no se puede deshacer.',
    ],
  },
  {
    id: 'dashboard',
    titulo: 'El Dashboard comercial',
    categoria: 'Reportes',
    keywords: 'dashboard tablero panel resumen mes ingresos contactos funnel canales seguimientos urgentes actividad reciente kpi indicadores inicio',
    pasos: [
      'Ve a "Dashboard" en el menú lateral (arriba). Muestra el resumen comercial del mes en curso.',
      'Arriba, 4 indicadores: nuevos contactos del mes, ingresos del mes vs el anterior, total por cobrar y seguimientos de la semana, cada uno con su meta.',
      'Más abajo: el funnel de avance por etapa y la actividad por canal (de dónde llegan tus clientes).',
      '"Ingresos por programa": cuánto entró por cada programa este mes vs el anterior, agrupado por nombre canónico.',
      '"Seguimientos urgentes": prospectos nuevos sin contacto +72h, con botones para accionar al instante (ver entrada propia).',
      '"Actividad reciente": el feed de los últimos movimientos del CRM.',
    ],
    tip: 'Empieza el día por el Dashboard: en 30 segundos sabes dónde está el dinero y a quién contactar ya.',
  },
  {
    id: 'seguimientos-urgentes',
    titulo: 'Accionar los Seguimientos urgentes del Dashboard',
    categoria: 'Seguimiento',
    keywords: 'urgentes urgente sin contacto 72 horas rojo dashboard whatsapp llamada correo registrar seguimiento prospecto nuevo accionar',
    pasos: [
      'En el Dashboard, busca la tarjeta "Seguimientos urgentes": prospectos nuevos (últimos 7 días) sin contacto hace +72h.',
      'Cada fila tiene botones de WhatsApp (con mensaje PNL listo), llamada y correo: contactas sin salir de la pantalla.',
      'El ícono ✓ abre un mini formulario para registrar el seguimiento (tipo + nota) ahí mismo.',
      'Al registrarlo, el prospecto sale de la lista y baja el contador rojo. Meta: dejarla en cero.',
    ],
    tip: 'Si ves un número alto, suele ser un lote de leads recién importados sin primer contacto. Trabájalos ese mismo día: un lead nuevo se enfría rápido.',
  },
  {
    id: 'cuota-fecha-real',
    titulo: 'Marcar una cuota pagada con su fecha real',
    categoria: 'Pagos',
    keywords: 'cuota pagada fecha real pago adelantado atrasado vencimiento plan cuotas comportamiento marcar editar calendario',
    pasos: [
      'Abre la ficha del cliente, pestaña "Actividades y pagos", y ubica el plan de cuotas.',
      'En la cuota, haz click en "Marcar pagada".',
      'Aparece un mini calendario con la fecha de vencimiento por defecto. Si la persona pagó otro día, edítalo a la fecha real.',
      'Confirma. El ingreso queda contabilizado en esa fecha, lo que te permite perfilar quién paga adelantado o atrasado.',
    ],
    tip: 'Registrar la fecha efectiva (no la de vencimiento) te da el comportamiento de pago real de cada cliente.',
  },
  {
    id: 'tipo-vs-actividad',
    titulo: 'Diferencia entre Tipo de cliente y Actividades',
    categoria: 'Clientes',
    keywords: 'tipo cliente actividad diferencia paciente alumni prospecto empresa asistente talleres taxonomia clasificacion catalogo asignar',
    pasos: [
      'El "Tipo de cliente" es QUIÉN es la persona para Renova: Paciente, Alumni, Asistente a talleres, Prospecto o Empresa/B2B. Se elige con chips en el modo completo.',
      'Las "Actividades" son EN QUÉ programa participa (diplomados, terapias, talleres, clases): se asignan en el campo aparte "Actividades".',
      'Al asignar una actividad, se registra sola en la pestaña Actividades del cliente para gestionarla; el tipo no crea actividades.',
      'Docente y Terapeuta no son tipos: son marcas aparte (🎓 / 🩺) que activan el flujo de boletas de honorarios.',
    ],
    tip: 'Regla simple: el tipo describe a la persona; la actividad describe lo que hace. No mezcles uno en el otro.',
  },
]
